version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    rust: "1.82"
    nodejs: "18"
  jobs:
    pre_build:
      # Copy the README.md file of each package into the docs directory
      - cp ./README.md docs/index.md

    # Potentially, this might be needed if there is content that will be
    # created from the pnpm package.
    # post_install:
    #   # Install any other extra dependencies to build the docs
    #   - npm install -g pnpm
    #   # Install dependencies defined in your ``package.json``
    #   - pnpm rust
    #   - pnpm dev


mkdocs:
  configuration: mkdocs.yml
